### ISSUE TITLE
cant get a client running

### ISSUE THREAD

**Issue by sneekyheart** [Dannark/BWO#16]
Hello Dannark,

Ive been looking around the web for an open-source mmorpg style game and your project fits my idea quite nicely.

I wanted to do some tests and i managed to get the server working but for no apparent reason i cant get a client apk or jar to roll out. it just keeps hitting back with all kinds of errors.
could you possibly make a step-by-step, or a quick guide to compile the client and use it for localhost test? i've tried using Heroku and Gitpod but i'm a real newbie when it comes to Git stuff.

**Comment by Dannark** [comment]
Hello mate,

Yeah it probably not going to work anymore without some fix. I built this game when Dark wasn't even released so a lot of changes has happned since then. I will take a look today and update the readme late on.

But to be honest, I'm not sure if this is the best start point for you to start your own project, It has a lot of features that might confuse you a bit. Wouldn't be nicer to have a sample starter project with just the basic for you or others to log in and walk around? Let me know what you think about it.

**Comment by sneekyheart** [comment]
Ahh alright, yeah I probably don't have the skills to fix it myself so if you'd be able to do that, that would be awesome!On Aug 14, 2021 13:34, Daniel Queiroz ***@***.***> wrote:
Hello mate,
Yeah it probably not going to work anymore without some fix. I built this game when Dark wasn't even released so a lot of changes has happned since then. I will take a look today and update the readme late on.
But to be honest, I'm not sure if this is the best start point for you to start your own project, It has a lot of features that might confuse you a bit. Wouldn't be nicer to have a sample starter project with just the basic for you or others to log in and walk around? Let me know what you think about it.

**Comment by Dannark** [comment]
Hi mate, 
I've been fixing some problems since yesterday but turns out now with flutter stable released all the dependencies are not going to work properly so the quickest way to get your client running is to downgrade your flutter to something like v1.22.6.

https://stackoverflow.com/a/49468364/2797044

I'm not sure if it worth update the entire project to the last version of flutter since a lot of dependencies has changed since then. I'm probably going to start a new project very soon with some benefits that I learned a lot from this project, and also because I want to improve some features. So I recommend you to keep an eye here

Let me know if you still have any problems
